services:
  iegeasycreditcardservice:
    image: iegeasycreditcardservice
    build:
      context: .
      dockerfile: IEGEasyCreditcardService/Dockerfile
    ports:
      - "7002:80"
      - "7003:443"
  meiShopService:
    image: meishopservice
    build:
      context: .
      dockerfile: MeiShop/Dockerfile
    ports:
      - "7000:80"
      - "7001:443"
