version: "3.4"

services:
  iegeasycreditcardservice:
    image: iegeasycreditcardservice
    restart: always
    build:
      context: .
      dockerfile: IEGEasyCreditcardService/Dockerfile
    ports:
      - "7002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  meiShopService:
    image: meishopservice
    restart: always
    build:
      context: .
      dockerfile: MeiShop/Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  productService:
    image: productservice
    restart: always
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "7004:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  productFTPService:
    image: productservice
    restart: always
    build:
      context: .
      dockerfile: ProductFtpService/Dockerfile
    ports:
      - "7006:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
